package butatopanto.kanji.bootstrap

class ChapterContent21 extends ChapterContent{

  ChapterContent21(){
    super(21)
  }

  @Override
  void addFramesToDatabase() {
    insertFrame(515, "地", "Grund")
    insertFrame(516, "池", "Teich")
    insertFrame(517, "虫", "Insekt")
    insertFrame(518, "蛍", "Glühwürmchen")
    insertFrame(519, "蛇", "Schlange")
    insertFrame(520, "虹", "Regenbogen")
    insertFrame(521, "蝶", "Schmetterling")
    insertFrame(522, "独", "allein")
    insertFrame(523, "蚕", "Seidenraupe")
    insertFrame(524, "風", "Wind")
    insertFrame(525, "己", "sich")
    insertFrame(526, "起", "aufwachen")
    insertFrame(527, "妃", "Königin")
    insertFrame(528, "改", "reformieren")
    insertFrame(529, "記", "notieren")
    insertFrame(530, "包", "einwickeln")
    insertFrame(531, "胞", "Plazente")
    insertFrame(532, "砲", "Kanone")
    insertFrame(533, "泡", "Schaum")
    insertFrame(534, "亀", "Schildkröte")
    insertFrame(535, "電", "Elektrizität")
    insertFrame(536, "竜", "Drache")
    insertFrame(537, "滝", "Wasserfall")
    insertFrame(538, "豚", "Schwein")
    insertFrame(539, "逐", "vertreiben")
    insertFrame(540, "遂", "durchführen")
    insertFrame(541, "家", "Haus")
    insertFrame(542, "嫁", "einheiraten")
    insertFrame(543, "豪", "grandios")
    insertFrame(544, "腸", "Gedärme")
    insertFrame(545, "場", "Ort")
    insertFrame(546, "湯", "Heißwasser")
    insertFrame(547, "羊", "Schaf")
    insertFrame(548, "美", "Schönheit")
    insertFrame(549, "洋", "Ozean")
    insertFrame(550, "詳", "detailliert")
    insertFrame(551, "鮮", "frisch")
    insertFrame(552, "達", "erlangen")
    insertFrame(553, "羨", "neidisch")
    insertFrame(554, "差", "Unterschied")
    insertFrame(555, "着", "anziehen")
    insertFrame(556, "唯", "bloß")
    insertFrame(557, "焦", "versengen")
    insertFrame(558, "礁", "Riff")
    insertFrame(559, "集", "sammeln")
    insertFrame(560, "准", "quasi-")
    insertFrame(561, "進", "Fortschritt")
    insertFrame(562, "雑", "divers")
    insertFrame(563, "雌", "weiblich")
    insertFrame(564, "準", "Semi-")
    insertFrame(565, "奮", "angeregt")
    insertFrame(566, "奪", "rauben")
    insertFrame(567, "確", "gewiss")
    insertFrame(568, "午", "Mittag")
    insertFrame(569, "許", "erlauben")
    insertFrame(570, "歓", "Freude")
    insertFrame(571, "権", "Autorität")
    insertFrame(572, "観", "Anschauung")
    insertFrame(573, "羽", "Feder")
    insertFrame(574, "習", "lernen")
    insertFrame(575, "翌", "folgender")
    insertFrame(576, "曜", "Wochentag")
    insertFrame(577, "濯", "spülen")
  }
}
