package butatopanto.kanji.bootstrap

class ChapterContent18 extends ChapterContent {

  ChapterContent18() {
    super(18)
  }

  public void addFramesToDatabase() {
    insertFrame(396, "衣", "Gewand")
    insertFrame(397, "裁", "schneidern")
    insertFrame(398, "装", "Aufmachung")
    insertFrame(399, "裏", "Rückseite")
    insertFrame(400, "壊", "zerstören")
    insertFrame(401, "哀", "Erbarmen")
    insertFrame(402, "遠", "fern")
    insertFrame(403, "猿", "Affe")
    insertFrame(404, "初", "erstmals")
    insertFrame(405, "布", "Stoff")
    insertFrame(406, "帆", "Segel")
    insertFrame(407, "幅", "Rollbild")
    insertFrame(408, "帽", "Mütze")
    insertFrame(409, "幕", "Vorhang")
    insertFrame(410, "幌", "Plane")
    insertFrame(411, "錦", "Brokat")
    insertFrame(412, "市", "Markt")
    insertFrame(413, "姉", "ältere Schwester")
    insertFrame(414, "肺", "Lunge")
    insertFrame(415, "帯", "Gurt")
    insertFrame(416, "滞", "stocken")
    insertFrame(417, "刺", "Stachel")
    insertFrame(418, "制", "System")
    insertFrame(419, "製", "herstellen")
    insertFrame(420, "転", "rotieren")
    insertFrame(421, "芸", "Kunst")
    insertFrame(422, "雨", "Regen")
    insertFrame(423, "雲", "Wolke")
    insertFrame(424, "曇", "bewölkt")
    insertFrame(425, "雷", "Donner")
    insertFrame(426, "霜", "Frost")
    insertFrame(427, "冬", "Winter")
    insertFrame(428, "天", "Himmel")
    insertFrame(429, "橋", "Brücke")
    insertFrame(430, "嬌", "attraktiv")
    insertFrame(431, "立", "stehen")
    insertFrame(432, "泣", "weinen")
    insertFrame(433, "章", "Abzeichen")
    insertFrame(434, "競", "konkurrieren")
    insertFrame(435, "帝", "Imperator")
    insertFrame(436, "童", "Knirps")
    insertFrame(437, "瞳", "Pupille")
    insertFrame(438, "鐘", "Glocke")
    insertFrame(439, "商", "Handel treiben")
    insertFrame(440, "嫡", "rechtmäßige Ehefrau")
    insertFrame(441, "適", "geeignet")
    insertFrame(442, "滴", "tropfen")
    insertFrame(443, "敵", "Feind")
    insertFrame(444, "匕", "Löffel")
    insertFrame(445, "北", "Norden")
    insertFrame(446, "背", "Statur")
    insertFrame(447, "比", "vergleichen")
    insertFrame(448, "昆", "Nachkomme")
    insertFrame(449, "皆", "alle")
    insertFrame(450, "混", "mischen")
    insertFrame(451, "渇", "Durst")
    insertFrame(452, "謁", "Audienz")
    insertFrame(453, "褐", "braun")
    insertFrame(454, "喝", "anbrüllen")
    insertFrame(455, "旨", "lecker")
    insertFrame(456, "脂", "Speck")
    insertFrame(457, "壱", "I. (eins)")
    insertFrame(458, "毎", "jedes Mal")
    insertFrame(459, "敏", "gewitzt")
    insertFrame(460, "梅", "Pflaume")
    insertFrame(461, "海", "Meer")
    insertFrame(462, "乞", "betteln")
    insertFrame(463, "乾", "Trockenheit")
    insertFrame(464, "腹", "Bauch")
    insertFrame(465, "複", "mehrfach")
    insertFrame(466, "欠", "Mangel")
    insertFrame(467, "吹", "blasen")
    insertFrame(468, "炊", "kochen")
    insertFrame(469, "歌", "Lied")
    insertFrame(470, "軟", "weich")
    insertFrame(471, "次", "Nächster")
    insertFrame(472, "茨", "Dornbusch")
    insertFrame(473, "資", "Kapital")
    insertFrame(474, "姿", "Figur")
    insertFrame(475, "諮", "zu Rate ziehen")
  }
}